# Generated by Django 6.0.4 on 2026-04-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_detallecompra_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('kg', 'Kilogramos'), ('g', 'Gramos'), ('l', 'Litros'), ('ml', 'Mililitros'), ('m', 'Metros'), ('cm', 'Centímetros'), ('u', 'Unidad'), ('docena', 'Docena'), ('paquete', 'Paquete'), ('lata', 'Lata'), ('botella', 'Botella'), ('caja', 'Caja')], default='u', max_length=20),
        ),
    ]
